package com.example.glitch.data;

import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.pdf.PdfDocument;

import androidx.annotation.NonNull;

import com.example.glitch.model.AccessEvent;
import com.example.glitch.model.AuditLogFilter;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.TimeZone;

/**
 * Simple on-device PDF renderer for filtered audit exports.
 */
final class AuditPdfBuilder {
    private static final int PAGE_WIDTH = 1240;
    private static final int PAGE_HEIGHT = 1754;
    private static final int MARGIN = 48;
    private static final int LINE_HEIGHT = 28;

    private AuditPdfBuilder() {
    }

    @NonNull
    static byte[] build(
            @NonNull List<AccessEvent> events,
            @NonNull AuditLogFilter filter,
            @NonNull String generatedByUid,
            @NonNull String generatedByRole,
            @NonNull String timezoneId
    ) throws IOException {
        PdfDocument document = new PdfDocument();
        Paint titlePaint = new Paint();
        titlePaint.setTextSize(22f);
        titlePaint.setFakeBoldText(true);

        Paint bodyPaint = new Paint();
        bodyPaint.setTextSize(12f);

        Paint monoPaint = new Paint();
        monoPaint.setTextSize(11f);

        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault());
        formatter.setTimeZone(TimeZone.getTimeZone(timezoneId));

        int pageIndex = 1;
        PdfDocument.Page page = document.startPage(new PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageIndex).create());
        Canvas canvas = page.getCanvas();
        int y = MARGIN;

        y = drawLine(canvas, "Glitch Audit Export", MARGIN, y, titlePaint, 0);
        y = drawLine(canvas, "Generated At: " + formatter.format(new Date()), MARGIN, y, bodyPaint, LINE_HEIGHT);
        y = drawLine(canvas, "Generated By: " + safe(generatedByUid) + " (" + safe(generatedByRole) + ")", MARGIN, y, bodyPaint, LINE_HEIGHT);
        y = drawLine(canvas, "Timezone: " + timezoneId, MARGIN, y, bodyPaint, LINE_HEIGHT);
        y = drawLine(canvas, "Range: " + formatter.format(new Date(filter.getFromInclusiveMillis()))
                + " -> " + formatter.format(new Date(filter.getToInclusiveMillis())), MARGIN, y, bodyPaint, LINE_HEIGHT);
        y = drawLine(canvas, "Types: " + filter.getEventTypes(), MARGIN, y, bodyPaint, LINE_HEIGHT);
        y = drawLine(canvas, "Roles: " + filter.getActorRoles(), MARGIN, y, bodyPaint, LINE_HEIGHT);
        y = drawLine(canvas, "Search: " + safe(filter.getSearchText()), MARGIN, y, bodyPaint, LINE_HEIGHT);
        y = drawLine(canvas, "Total Rows: " + events.size(), MARGIN, y, bodyPaint, LINE_HEIGHT);
        y += LINE_HEIGHT;
        y = drawLine(canvas, "Time | Type | Outcome | Actor | Entity | Description", MARGIN, y, monoPaint, 0);
        y += LINE_HEIGHT / 2;

        for (AccessEvent event : events) {
            if (y >= PAGE_HEIGHT - (MARGIN + LINE_HEIGHT)) {
                document.finishPage(page);
                pageIndex++;
                page = document.startPage(new PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageIndex).create());
                canvas = page.getCanvas();
                y = MARGIN;
                y = drawLine(canvas, "Audit Events (continued)", MARGIN, y, titlePaint, 0);
                y += LINE_HEIGHT;
                y = drawLine(canvas, "Time | Type | Outcome | Actor | Entity | Description", MARGIN, y, monoPaint, 0);
                y += LINE_HEIGHT / 2;
            }

            String timestamp = event.getCreatedAt() == null
                    ? "N/A"
                    : formatter.format(event.getCreatedAt().toDate());
            String row = truncate(
                    timestamp + " | "
                            + safe(event.getEventType()) + " | "
                            + safe(event.getOutcome()) + " | "
                            + safe(event.getActorUid()) + "/" + safe(event.getActorRole()) + " | "
                            + safe(event.getCorrelationId()) + " | "
                            + safe(event.getDescription()),
                    170
            );
            y = drawLine(canvas, row, MARGIN, y, monoPaint, LINE_HEIGHT);
        }

        document.finishPage(page);
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        document.writeTo(outputStream);
        document.close();
        return outputStream.toByteArray();
    }

    private static int drawLine(
            @NonNull Canvas canvas,
            @NonNull String text,
            int x,
            int y,
            @NonNull Paint paint,
            int yIncrement
    ) {
        canvas.drawText(text, x, y, paint);
        return y + (yIncrement <= 0 ? LINE_HEIGHT : yIncrement);
    }

    @NonNull
    private static String truncate(@NonNull String value, int maxChars) {
        if (value.length() <= maxChars) {
            return value;
        }
        return value.substring(0, Math.max(0, maxChars - 3)) + "...";
    }

    @NonNull
    private static String safe(@NonNull String value) {
        String trimmed = value.trim();
        return trimmed.isEmpty() ? "N/A" : trimmed;
    }
}
