package com.example.glitch.model;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.google.firebase.Timestamp;

import java.util.Map;

/**
 * Represents an automated security alert generated by repeated failures.
 * Pattern: Immutable POJO for admin alerts monitoring UI.
 * Known issue: alert severity uses simple text levels in v1.
 */
public class SecurityAlert {
	private final String id;
	private final String alertType;
	private final String identifier;
	private final int failCount;
	private final String severity;
	private final String message;
	private final String entryRequestId;
	private final String reportedByUid;
	private final String reportedByRole;
	private final String reportedByName;
	private final String guestName;
	private final String guestIdNumber;
	private final String guestPhone;
	private final String hostName;
	private final String requesterUid;
	private final String requesterRole;
	private final String gateLabel;
	private final String reasonCode;
	private final String source;
	private final String incidentStatus;
	private final String interventionSummary;
	private final String violationReportId;
	private final String vehicleRequestId;
	private final String chargeId;
	private final String guestPassId;
	private final String subjectStudentId;
	private final Timestamp createdAt;

	/**
	 * Creates an immutable security alert model.
	 */
	public SecurityAlert(
			@NonNull String id,
			@NonNull String alertType,
			@NonNull String identifier,
			int failCount,
			@NonNull String severity,
			@NonNull String message,
			@NonNull String entryRequestId,
			@NonNull String reportedByUid,
			@NonNull String reportedByRole,
			@NonNull String reportedByName,
			@NonNull String guestName,
			@NonNull String guestIdNumber,
			@NonNull String guestPhone,
			@NonNull String hostName,
			@NonNull String requesterUid,
			@NonNull String requesterRole,
			@NonNull String gateLabel,
			@NonNull String reasonCode,
			@NonNull String source,
			@NonNull String incidentStatus,
			@NonNull String interventionSummary,
			@NonNull String violationReportId,
			@NonNull String vehicleRequestId,
			@NonNull String chargeId,
			@NonNull String guestPassId,
			@NonNull String subjectStudentId,
			@Nullable Timestamp createdAt
	) {
		this.id = id;
		this.alertType = alertType;
		this.identifier = identifier;
		this.failCount = failCount;
		this.severity = severity;
		this.message = message;
		this.entryRequestId = entryRequestId;
		this.reportedByUid = reportedByUid;
		this.reportedByRole = reportedByRole;
		this.reportedByName = reportedByName;
		this.guestName = guestName;
		this.guestIdNumber = guestIdNumber;
		this.guestPhone = guestPhone;
		this.hostName = hostName;
		this.requesterUid = requesterUid;
		this.requesterRole = requesterRole;
		this.gateLabel = gateLabel;
		this.reasonCode = reasonCode;
		this.source = source;
		this.incidentStatus = incidentStatus;
		this.interventionSummary = interventionSummary;
		this.violationReportId = violationReportId;
		this.vehicleRequestId = vehicleRequestId;
		this.chargeId = chargeId;
		this.guestPassId = guestPassId;
		this.subjectStudentId = subjectStudentId;
		this.createdAt = createdAt;
	}

	/**
	 * Maps Firestore document data into a {@link SecurityAlert}.
	 *
	 * @param id Firestore document id.
	 * @param map Firestore field map.
	 * @return parsed alert object or empty fallback if map is null.
	 */
	@NonNull
	public static SecurityAlert fromMap(@NonNull String id, @Nullable Map<String, Object> map) {
		if (map == null) {
			return new SecurityAlert(
					id,
					"",
					"",
					0,
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					null
			);
		}
		String alertType = asString(map.get("alertType"));
		String entryRequestId = asString(map.get("entryRequestId"));
		String identifier = asString(map.get("identifier"));
		if (identifier.trim().isEmpty() && !entryRequestId.trim().isEmpty()) {
			identifier = entryRequestId;
		}
		return new SecurityAlert(
				id,
				alertType,
				identifier,
				asInt(map.get("failCount")),
				asString(map.get("severity")),
				asString(map.get("message")),
				entryRequestId,
				asString(map.get("reportedByUid")),
				asString(map.get("reportedByRole")),
				asString(map.get("reportedByName")),
				asString(map.get("guestName")),
				asString(map.get("guestIdNumber")),
				asString(map.get("guestPhone")),
				asString(map.get("hostName")),
				asString(map.get("requesterUid")),
				asString(map.get("requesterRole")),
				asString(map.get("gateLabel")),
				asString(map.get("reportReasonCode")),
				asString(map.get("reportSource")),
				asString(map.get("incidentStatus")),
				asString(map.get("interventionSummary")),
				asString(map.get("violationReportId")),
				asString(map.get("vehicleRequestId")),
				asString(map.get("chargeId")),
				asString(map.get("guestPassId")),
				asString(map.get("subjectStudentId")),
				asTimestamp(map.get("createdAt"))
		);
	}

	/**
	 * @return Firestore alert document id.
	 */
	@NonNull
	public String getId() {
		return id;
	}

	@NonNull
	public String getAlertType() {
		return alertType;
	}

	/**
	 * @return failing identifier tied to this alert.
	 */
	@NonNull
	public String getIdentifier() {
		return identifier;
	}

	/**
	 * @return number of failed verification attempts counted for the identifier.
	 */
	public int getFailCount() {
		return failCount;
	}

	/**
	 * @return severity label (for example MEDIUM/HIGH).
	 */
	@NonNull
	public String getSeverity() {
		return severity;
	}

	/**
	 * @return descriptive message shown on admin alerts surface.
	 */
	@NonNull
	public String getMessage() {
		return message;
	}

	@NonNull
	public String getEntryRequestId() {
		return entryRequestId;
	}

	@NonNull
	public String getReportedByUid() {
		return reportedByUid;
	}

	@NonNull
	public String getReportedByRole() {
		return reportedByRole;
	}

	@NonNull
	public String getReportedByName() {
		return reportedByName;
	}

	@NonNull
	public String getGuestName() {
		return guestName;
	}

	@NonNull
	public String getGuestIdNumber() {
		return guestIdNumber;
	}

	@NonNull
	public String getGuestPhone() {
		return guestPhone;
	}

	@NonNull
	public String getHostName() {
		return hostName;
	}

	@NonNull
	public String getRequesterUid() {
		return requesterUid;
	}

	@NonNull
	public String getRequesterRole() {
		return requesterRole;
	}

	@NonNull
	public String getGateLabel() {
		return gateLabel;
	}

	@NonNull
	public String getReasonCode() {
		return reasonCode;
	}

	@NonNull
	public String getSource() {
		return source;
	}

	@NonNull
	public String getIncidentStatus() {
		return incidentStatus;
	}

	@NonNull
	public String getInterventionSummary() {
		return interventionSummary;
	}

	@NonNull
	public String getViolationReportId() {
		return violationReportId;
	}

	@NonNull
	public String getVehicleRequestId() {
		return vehicleRequestId;
	}

	@NonNull
	public String getChargeId() {
		return chargeId;
	}

	@NonNull
	public String getGuestPassId() {
		return guestPassId;
	}

	@NonNull
	public String getSubjectStudentId() {
		return subjectStudentId;
	}

	public boolean isEntryReportAlert() {
		return "entry_report".equalsIgnoreCase(alertType);
	}

	/**
	 * @return Firestore-created timestamp when the alert was recorded.
	 */
	@Nullable
	public Timestamp getCreatedAt() {
		return createdAt;
	}

	@NonNull
	private static String asString(@Nullable Object value) {
		return value == null ? "" : String.valueOf(value);
	}

	private static int asInt(@Nullable Object value) {
		if (value instanceof Number) {
			return ((Number) value).intValue();
		}
		return 0;
	}

	@Nullable
	private static Timestamp asTimestamp(@Nullable Object value) {
		if (value instanceof Timestamp) {
			return (Timestamp) value;
		}
		return null;
	}
}
