package com.example.glitch.model;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.google.firebase.Timestamp;

import java.util.Map;

/**
 * Represents an automated security alert generated by repeated failures.
 * Pattern: Immutable POJO for admin alerts monitoring UI.
 * Known issue: alert severity uses simple text levels in v1.
 */
public class SecurityAlert {
	private final String id;
	private final String identifier;
	private final int failCount;
	private final String severity;
	private final String message;
	private final Timestamp createdAt;

	/**
	 * Creates an immutable security alert model.
	 */
	public SecurityAlert(
			@NonNull String id,
			@NonNull String identifier,
			int failCount,
			@NonNull String severity,
			@NonNull String message,
			@Nullable Timestamp createdAt
	) {
		this.id = id;
		this.identifier = identifier;
		this.failCount = failCount;
		this.severity = severity;
		this.message = message;
		this.createdAt = createdAt;
	}

	/**
	 * Maps Firestore document data into a {@link SecurityAlert}.
	 *
	 * @param id Firestore document id.
	 * @param map Firestore field map.
	 * @return parsed alert object or empty fallback if map is null.
	 */
	@NonNull
	public static SecurityAlert fromMap(@NonNull String id, @Nullable Map<String, Object> map) {
		if (map == null) {
			return new SecurityAlert(id, "", 0, "", "", null);
		}
		return new SecurityAlert(
				id,
				asString(map.get("identifier")),
				asInt(map.get("failCount")),
				asString(map.get("severity")),
				asString(map.get("message")),
				asTimestamp(map.get("createdAt"))
		);
	}

	/**
	 * @return Firestore alert document id.
	 */
	@NonNull
	public String getId() {
		return id;
	}

	/**
	 * @return failing identifier tied to this alert.
	 */
	@NonNull
	public String getIdentifier() {
		return identifier;
	}

	/**
	 * @return number of failed verification attempts counted for the identifier.
	 */
	public int getFailCount() {
		return failCount;
	}

	/**
	 * @return severity label (for example MEDIUM/HIGH).
	 */
	@NonNull
	public String getSeverity() {
		return severity;
	}

	/**
	 * @return descriptive message shown on admin alerts surface.
	 */
	@NonNull
	public String getMessage() {
		return message;
	}

	/**
	 * @return Firestore-created timestamp when the alert was recorded.
	 */
	@Nullable
	public Timestamp getCreatedAt() {
		return createdAt;
	}

	@NonNull
	private static String asString(@Nullable Object value) {
		return value == null ? "" : String.valueOf(value);
	}

	private static int asInt(@Nullable Object value) {
		if (value instanceof Number) {
			return ((Number) value).intValue();
		}
		return 0;
	}

	@Nullable
	private static Timestamp asTimestamp(@Nullable Object value) {
		if (value instanceof Timestamp) {
			return (Timestamp) value;
		}
		return null;
	}
}